<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_navTabButtonUserInfoProfil</name>
   <tag></tag>
   <elementGuidId>948f4629-24e5-42c7-9e70-431ee228bab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;navTabButtonChangeProfileImageLink&quot;)/img[@class=&quot;navTabButtonUserInfoProfileImage&quot;][count(. | //img[contains(@alt, 'Waste Test 1 AG-EA-LP-QA-MASTER') and @class = 'navTabButtonUserInfoProfileImage']) = count(//img[contains(@alt, 'Waste Test 1 AG-EA-LP-QA-MASTER') and @class = 'navTabButtonUserInfoProfileImage'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Waste Test 1 AG-EA-LP-QA-MASTER</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_imgs/navbar/emptyuserimage.png?ver=1055748802</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navTabButtonUserInfoProfileImage</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navTabButtonChangeProfileImageLink&quot;)/img[@class=&quot;navTabButtonUserInfoProfileImage&quot;]</value>
   </webElementProperties>
</WebElementEntity>
