<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_navTabButtonChangeProfile</name>
   <tag></tag>
   <elementGuidId>e2a822f6-b309-4528-a22f-605e311bea8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;navTabButtonChangeProfileImageLink&quot;)[count(. | //span[@id = 'navTabButtonChangeProfileImageLink' and @class = 'navTabButtonImageContainer']) = count(//span[@id = 'navTabButtonChangeProfileImageLink' and @class = 'navTabButtonImageContainer'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;navTabButtonChangeProfileImageLink&quot;)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navTabButtonChangeProfileImageLink</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navTabButtonImageContainer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navTabButtonChangeProfileImageLink&quot;)</value>
   </webElementProperties>
</WebElementEntity>
