<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_WE0003QAA001</name>
   <tag></tag>
   <elementGuidId>62d1918d-d234-481f-ac96-2a26d3e6cfea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'attribone' and (text() = 'WE0003QA/A001' or . = 'WE0003QA/A001') and @ref_element = 'Object Repository/FrontEnd/Page_Microsoft Dynamics 365/iframe_contentIFrame1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attribone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WE0003QA/A001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Record_10013_4cd0d0bddc37e811a95e000d3a233e06&quot;)/div[@class=&quot;section listItem_section image_enabled_meqf listItemMargin listItemMarginDisplay&quot;]/div[@class=&quot;section_control_meqf noLabel&quot;]/div[@class=&quot;control_value attributePrimary keyboardFocusClass&quot;]/span[@id=&quot;attribone&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/FrontEnd/Page_Microsoft Dynamics 365/iframe_contentIFrame1</value>
   </webElementProperties>
</WebElementEntity>
