<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Na</name>
   <tag></tag>
   <elementGuidId>9fa24753-b9ab-492b-ad21-99783e163ebe</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gwt-uid-115</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>N/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;landscape&quot;]/div[@class=&quot;GKH2EKQBOBB GKH2EKQBACB&quot;]/div[@class=&quot;GKH2EKQBOBB GKH2EKQBACB&quot;]/div[@class=&quot;GKH2EKQBDHB&quot;]/div[@class=&quot;GKH2EKQBCHB&quot;]/div[@class=&quot;GKH2EKQBFHB&quot;]/div[@class=&quot;GKH2EKQBEHB&quot;]/div[@class=&quot;GKH2EKQBOBB GKH2EKQBLGB&quot;]/div[@class=&quot;GKH2EKQBMDC GKH2EKQBMGB GKH2EKQBNGB&quot;]/div[1]/div[@class=&quot;GKH2EKQBOBB&quot;]/div[@class=&quot;GKH2EKQBOBB GKH2EKQBM4B GKH2EKQBI4B GKH2EKQBPGC&quot;]/div[2]/div[@class=&quot;GKH2EKQBOBB&quot;]/span[@class=&quot;gwt-RadioButton GKH2EKQBFGC&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
