<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_crmGrid_findCriteria</name>
   <tag></tag>
   <elementGuidId>b801ee9d-c918-4d5e-bedc-10ede591cf33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;crmGrid_findCriteria&quot;)[count(. | //input[@id = 'crmGrid_findCriteria' and @title = 'Search for records' and @hintlabelid = 'crmGrid_findHintText' and @type = 'text' and @class = 'ms-crm-Dialog-Lookup-QuickFind' and @ref_element = 'Object Repository/CRMBack/Page_Applications Active Applicatio/iframe_contentIFrame0']) = count(//input[@id = 'crmGrid_findCriteria' and @title = 'Search for records' and @hintlabelid = 'crmGrid_findHintText' and @type = 'text' and @class = 'ms-crm-Dialog-Lookup-QuickFind' and @ref_element = 'Object Repository/CRMBack/Page_Applications Active Applicatio/iframe_contentIFrame0'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>crmGrid_findCriteria</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search for records</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hintlabelid</name>
      <type>Main</type>
      <value>crmGrid_findHintText</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-Dialog-Lookup-QuickFind</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crmGrid_findCriteria&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CRMBack/Page_Applications Active Applicatio/iframe_contentIFrame0</value>
   </webElementProperties>
</WebElementEntity>
