<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>8fae2615-7c1a-47a9-a896-277a155b2954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;crmGrid_findCriteriaButton&quot;)/span[1][count(. | //span[@ref_element = 'Object Repository/CRMBack/Page_Applications Active Applicatio/iframe_contentIFrame0']) = count(//span[@ref_element = 'Object Repository/CRMBack/Page_Applications Active Applicatio/iframe_contentIFrame0'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crmGrid_findCriteriaButton&quot;)/span[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CRMBack/Page_Applications Active Applicatio/iframe_contentIFrame0</value>
   </webElementProperties>
</WebElementEntity>
